var geld= 125;
var map = [[[9, ['Bilder/Map/feld2.jpg','Bilder/Map/ziel1.png']],[2, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[17, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal2.png'],10,8],[9, ['Bilder/Map/weg3.png','Bilder/Map/ziel1.png']],], 
[[16, ['Bilder/Map/feld2.jpg','Bilder/Map/zwischenPortal2.png'],6,7],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[-2, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[3, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[13, ['Bilder/Map/feld2.jpg','Bilder/Map/zwischenPortal2.png'],8,10],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[15, ['Bilder/Map/feld2.jpg','Bilder/Map/zwischenPortal2.png'],7,6],[8, ['Bilder/Map/feld2.jpg','Bilder/Map/start.png']],[5, ['Bilder/Map/feld2.jpg','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[2, 'Bilder/Map/weg3.png'],[-2, 'Bilder/Map/weg3.png'],[-2, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[3, 'Bilder/Map/weg3.png'],[7, ['Bilder/Map/feld2.jpg','Bilder/Map/start.png']],[6, ['Bilder/Map/feld2.jpg','Bilder/Map/start.png']],[13, ['Bilder/Map/feld2.jpg','Bilder/Map/zwischenPortal2.png'],2,3],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[3, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[2, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[17, ['Bilder/Map/feld2.jpg','Bilder/Map/zwischenPortal2.png'],4,12],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],], 
[[2, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[2, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[2, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[-2, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[1, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg2.jpg'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld1.jpg'],], 
[[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[-2, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/feld2.jpg'],[14, ['Bilder/Map/weg2.jpg','Bilder/Map/zwischenPortal2.png'],3,2],], 
[[9, ['Bilder/Map/weg1.jpg','Bilder/Map/ziel1.png']],[15, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal2.png'],12,4],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/feld2.jpg'],[9, ['Bilder/Map/weg2.jpg','Bilder/Map/ziel1.png']],], 
]
;
success= true;
mapSchwie= 4;
MapName = 'Wirr - Warr';
multiStartTyp = 2;
if(!mapSchwie) mapSchwie = 'undefined';if(!MapName) MapName = 'undefined';if(!multiStartTyp) multiStartTyp = 'undefined';var randomtiles = true



 // hier kommt das preview- Bild 


var image = 'Maps/map_181600707693428Bild/Bild.png';
