var geld= 100;
var map = [[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],], 
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[5, ['Bilder/Map/feld1.jpg','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[9, ['Bilder/Map/feld1.jpg','Bilder/Map/ziel1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
]
;
success= true;
mapSchwie= 4;
MapName = "Creative!!!!! Ain't I?";
multiStartTyp = 0;
if(!mapSchwie) mapSchwie = 'undefined';if(!MapName) MapName = 'undefined';if(!multiStartTyp) multiStartTyp = 'undefined';var randomtiles = false



 // hier kommt das preview- Bild 


var image = 'Maps/map12/image.webp';
