var geld = 75;
var map = [[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[6, ['Bilder/Map/weg1.jpg','Bilder/Map/start.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[13, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal1.png'],3,2],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[16, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal2.png'],5,4],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[14, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal1.png'],2,1],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[9, ['Bilder/Map/weg1.jpg','Bilder/Map/ziel1.png']],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[16, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal2.png'],4,5],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[13, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal1.png'],1,2],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[8, ['Bilder/Map/weg1.jpg','Bilder/Map/start.png']],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
]
;
success= true;
mapSchwie = false;
MapName = 'false';
multiStartTyp = 0;
if(!mapSchwie) mapSchwie = 'undefined';if(!MapName) MapName = 'undefined';if(!multiStartTyp) multiStartTyp = 'undefined';var randomtiles = false



 // hier kommt das preview- Bild


var image = 'Bilder/mapVorschau/Map14.webp';
