var geld= 75;
var map = [[[5, ['Bilder/Map/weg3.png','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[14, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],3,5],[14, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],4,6],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[7, ['Bilder/Map/weg3.png','Bilder/Map/start.png']],], 
[[17, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],5,3],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[15, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],6,4],], 
[[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg1.jpg'],], 
[[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg1.jpg'],], 
[[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg1.jpg'],], 
[[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],], 
[[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[9, ['Bilder/Map/weg3.png','Bilder/Map/ziel1.png']],[9, ['Bilder/Map/weg3.png','Bilder/Map/ziel1.png']],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],], 
[[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[9, ['Bilder/Map/weg3.png','Bilder/Map/ziel1.png']],[9, ['Bilder/Map/weg3.png','Bilder/Map/ziel1.png']],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],], 
[[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],], 
[[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg1.jpg'],], 
[[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg1.jpg'],], 
[[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[0, 'Bilder/Map/weg3.png'],[2, 'Bilder/Map/weg1.jpg'],], 
[[17, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],8,1],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[15, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],7,2],], 
[[5, ['Bilder/Map/weg3.png','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[16, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],1,8],[16, ['Bilder/Map/weg3.png','Bilder/Map/zwischenPortal1.png'],2,7],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[7, ['Bilder/Map/weg3.png','Bilder/Map/start.png']],], 
]
;
success= true;
mapSchwie= 4;
MapName = '';
multiStartTyp = 2;
if(!mapSchwie) mapSchwie = 'undefined';if(!MapName) MapName = 'undefined';if(!multiStartTyp) multiStartTyp = 'undefined';var randomtiles = false



 // hier kommt das preview- Bild 


var image = 'Maps/map_161599630705744Bild/Bild.png';