var geld = 75;
var map = [[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[5, ['Bilder/Map/weg1.jpg','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[13, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal1.png'],1,2],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[13, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal2.png'],4,3],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[14, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal1.png'],2,1],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[9, ['Bilder/Map/weg1.jpg','Bilder/Map/ziel1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[14, ['Bilder/Map/weg1.jpg','Bilder/Map/zwischenPortal2.png'],3,4],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein2.png']],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein3.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],],
]
;
success= true;
mapSchwie = false;
MapName = 'false';
multiStartTyp = 0;
if(!mapSchwie) mapSchwie = 'undefined';if(!MapName) MapName = 'undefined';if(!multiStartTyp) multiStartTyp = 'undefined';var randomtiles = false



 // hier kommt das preview- Bild


var image = 'Bilder/mapVorschau/Map20.png';
