var geld= 75;
var map = [[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[5, ['Bilder/Map/feld1.jpg','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[9, ['Bilder/Map/feld1.jpg','Bilder/Map/ziel1.png']],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],],
[[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld1.jpg'],],
]
;
success= true;
mapSchwie= 1;
MapName = "Dosenfisch";
multiStartTyp = 0;
var randomtiles = false



 // hier kommt das preview- Bild


var image = 'Bilder/MapVorschau/Map5.webp';
