var geld= 75;
var map = [[[5, ['Bilder/Map/feld1.jpg','Bilder/Map/start.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld2.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[0, 'Bilder/Map/feld2.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[-2, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[0, 'Bilder/Map/feld2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[0, 'Bilder/Map/feld2.jpg'],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[1, 'Bilder/Map/weg1.jpg'],[4, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],[2, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
[[11, ['Bilder/Map/feld1.jpg','Bilder/Map/ziel1.png']],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[3, 'Bilder/Map/weg1.jpg'],[-1, ['Bilder/Map/feld1.jpg','Bilder/Map/stein1.png']],], 
]
;
success= true;
var randomtiles = false
var multiStartTyp = "0";



 // hier kommt das preview- Bild 


var image = 'Maps/map8/image.png';
